# permissions for end users to view firmwares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firmware-viewer-role
rules:
- apiGroups:
  - octeon.my.domain
  resources:
  - firmwares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - octeon.my.domain
  resources:
  - firmwares/status
  verbs:
  - get
