apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: octeon-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Firmware is the Schema for the firmwares API
      displayName: Firmware
      kind: Firmware
      name: firmwares.octeon.marvell.com
      version: v1alpha1
  description: The operator will manage firmware running on Octeon family of DPUs
  displayName: Octeon Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - octeon
  - dpu
  links:
  - name: Octeon Operator
    url: https://octeon-operator.domain
  maturity: alpha
  provider:
    name: Marvell
    url: www.marvell.com
  version: 0.0.0
